{% set name = "torchange" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchange-{{ version }}.tar.gz
  sha256: 1019e942000efc3aafe7bcfc6b77656574893bce276f9a2215beb727344990a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - albumentations >=0.4.2
    - tifffile
    - scikit-image
    - tqdm
    - einops
    - timm
    - datasets
    - ever-beta

test:
  imports:
    - torchange
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Z-Zheng/pytorch-change-models
  summary: A Unified Change Representation Learning Benchmark Library
  description: A Unified Change Representation Learning Benchmark Library
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/Z-Zheng/pytorch-change-models

extra:
  recipe-maintainers:
    - giswqs
